name: firebase_admob_config
description: Control google admob by firebase remote config
version: 1.0.0
homepage: https://github.com/hautvfami

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #  google_mobile_ads: ^0.13.2+1
  #  firebase_remote_config: ^0.10.0+3
  google_mobile_ads:
  firebase_remote_config:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  #  json_annotation: ^4.0.1
  #  json_serializable: ^4.1.3
  #  build_runner: ^2.0.6
  json_annotation:
  json_serializable:
  build_runner:

flutter: