name: firebase_admob_config
description: Control google admob by firebase remote config. This package help you can config AdMob ads with Firebase Remote Config and A/B testing on them.
version: 1.1.0
homepage: https://github.com/hautvfami
repository: https://github.com/hautvfami/firebase_admob_config

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.0.1
  google_mobile_ads: ^1.2.0
  firebase_remote_config: ^2.0.7
#  google_mobile_ads:
#  firebase_remote_config:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  json_serializable: ^4.1.3
  build_runner: ^2.0.6

flutter: